Revert "[v8-platform] Store the platform in a unique_ptr"
This reverts commit 608e8dd6b87b15772862dca9b7b2e6791a25dab6.

Reason for revert: Breaks the roll into Chromium

pdf/pdfium/fuzzers/pdfium_fuzzer_helper.cc:238:5: error: no matching function for call to 'InitializeV8ForPDFium'
    InitializeV8ForPDFium(ProgramPath(), "", &natives_blob, &snapshot_blob,
    ^~~~~~~~~~~~~~~~~~~~~
../../third_party/pdfium/testing/test_support.h:94:31: note: candidate function not viable: requires 4 arguments, but 5 were provided
std::unique_ptr<v8::Platform> InitializeV8ForPDFium(
                              ^

https://logs.chromium.org/v/?s=chromium%2Fbb%2Ftryserver.chromium.linux%2Flinux_chromium_compile_dbg_ng%2F461077%2F%2B%2Frecipes%2Fsteps%2Fcompile__with_patch_%2F0%2Fstdout



Original change's description:
> [v8-platform] Store the platform in a unique_ptr
> 
> We want to change the signature of {CreateDefaultPlatform} in the V8
> API to return a unique_ptr instead of a raw pointer to indicate that the
> caller owns the platform. With this change we prepare pdfium for this
> change.
> 
> R=​thestig@chromium.org
> 
> Change-Id: I4a0a466dfc37b28387a91543623a7a481ca8035a
> Reviewed-on: https://pdfium-review.googlesource.com/18191
> Commit-Queue: Lei Zhang <thestig@chromium.org>
> Reviewed-by: Lei Zhang <thestig@chromium.org>

TBR=thestig@chromium.org,ahaas@chromium.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Change-Id: I418c97653e8aba93560537f0d41e1aaa238bf3b4
Reviewed-on: https://pdfium-review.googlesource.com/25850
Commit-Queue: dsinclair <dsinclair@chromium.org>
Reviewed-by: dsinclair <dsinclair@chromium.org>