Add missing parenthesis in FXARGB_GETDIB macro
You can get warning when using FXARGB_GETDIB() with & operation in
the same statement like: FXARGB_GETDIB(src_scan) & 0xffffff in
fx_dib_composite.cpp:

../../third_party/pdfium/core/src/fxge/dib/fx_dib_composite.cpp:737:205:
error: '&' within '|' [-Werror,-Wbitwise-op-parentheses]

Original patch from jiangj@opera.com

R=thakis@chromium.org

Review URL: https://codereview.chromium.org/578253002