Pdfium_unittests: Fix undefined reference to testing::Matcher
The pdfium_unittest target currently fails to build because of an
undefined reference to gtest's matchers.

Fix this by including gtest-matchers.{h,cpp} in gtest's source_set.

Change-Id: I4dffd1e924cc48b013504dcdfdf7b702c47b4780
Reviewed-on: https://pdfium-review.googlesource.com/c/50451
Reviewed-by: Lei Zhang <thestig@chromium.org>
Commit-Queue: Lei Zhang <thestig@chromium.org>