Fix Wvarargs warning in XFA error code.
Chrome has enabled the -Wvarargs warning that was added to clang, this fails
with PDFium XFA builds due to two warnings:

../../xfa/fxfa/fm2js/xfa_lexer.cpp:539:16: error: passing an object that
undergoes default argument promotion to 'va_start' has undefined behavior
[-Werror,-Wvarargs]
  va_start(ap, msg);
               ^
../../xfa/fxfa/fm2js/xfa_lexer.cpp:535:40: note: parameter of type
'XFA_FM_ERRMSG' is declared here
void CXFA_FMLexer::Error(XFA_FM_ERRMSG msg, ...) {

The issue is that XFA_FM_ERRMSG is an enum and we violate the promotion rules
for passing the value to va_start.

I removed the enum and named the flags explicitly then pass in the string as
the argument.

BUG=chromium:606726

Review URL: https://codereview.chromium.org/1921323002