fdrm: fix MSVC 2019 build
This fixes the following build error:

core/fdrm/fx_crypt_aes.cpp(444): error C4005: 'MAKEWORD': macro redefinition
C:\PROGRA~2\WI3CF2~1\10\Include\10.0.18362.0\shared\minwindef.h(202): note: see previous definition of 'MAKEWORD'

Just give the usual "F" prefix to the MAKEWORD macro to avoid conflict
with the Windows SDK.

Change-Id: Ie7b429de9419f5856635b2ccc45b7f3f4603d48b
Reviewed-on: https://pdfium-review.googlesource.com/c/pdfium/+/85250
Commit-Queue: Lei Zhang <thestig@chromium.org>
Reviewed-by: Lei Zhang <thestig@chromium.org>